### ISSUE TITLE
put请求不行

### ISSUE THREAD

**Issue by shenshangjimiaoZG** [lztbwlkj/MSNetwork#2]
你封装的put请求不行，后台接收不到参数。直接用afnetworking的put就可以，请修改。
你的msnetwork和hjnetwork都差不多。目前测试put的传参不行。

**Comment by milletpeak** [comment]
收到 我尽快测试修改

**Comment by shenshangjimiaoZG** [comment]
是否在等hjnetwork修复 再修复 哈哈

**Comment by milletpeak** [comment]
抱歉！真的很抱歉 ！最近是在太忙抽不开身！这个问题您可以暂时先将参数拼接到地址后面传给后台eg:/service/dabaojian?name=ms&pwd=123456,
